name: Node.js Package
on:
  create
jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          registry-url: 'https://registry.npmjs.org'
      - run: |
          npm install --global rollup
          mkdir dist
          cd js
          rollup zdict.js --format umd --name zDict --file ../dist/zdict.js
          rollup learn-chars.js --format iife --file ../dist/learn-chars.js
          # rollup data-chars.js --format cjs --file ../dist/data-chars.js
          # rollup data-freqs.js --format cjs --file ../dist/data-freqs.js
          cd ..
          rm -r js/ R/ data/ *.Rproj
          mv dist js
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
