name: Node.js Package
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          registry-url: 'https://registry.npmjs.org'
      - run: |
          npm install --global rollup
          cd js
          rollup zdict.js --format umd --name zDict --file zdict2.js
          mv zdict2.js zdict.js
          # rollup data-chars.js --format cjs --file data-chars2.js
          # rollup data-freqs.js --format cjs --file data-freqs2.js
          cd ..
          rm -r R/ data/ *.Rproj
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
